### ISSUE TITLE
Roadmap and Ideas

### ISSUE THREAD

**Issue by mahdiboomeri** [mahdiboomeri/nuxt-query#1]
Most of the inspiration came from `@tanstack/query`. 
I thought about just using the [Vue adaptor](https://vue-query.vercel.app/) however that's an additional dependency in the bundle, Nuxt already has a similar API which is well integrated with Nuxt itself.

### Motivation
This module is supposed to be a collection of mostly syntax sugars for patterns I saw myself reinventing in a large project using Nuxt 3 `useAsyncData`. 

### Goals

- Minimum bundle cost (aiming for less than 5KB)
- Drop-in replacement for `useAsyncData` (no changing behaviors, only adding things)

### Roadmap and Ideas
- [x] #6
- [ ] `useMutation`
- [x] #7
- [ ] `useInfiniteQuery`
- [x] #4
- [x] #15
- [ ] Refresh data base on key patterns
- [x] #8
- [x] #12
- [ ] new `fetchStatus` enum => `'fetching' | 'paused' | 'idle'`
- [x] #17
- [ ] network mode => e.g. `refetchOnOnline`
- [x] #10
- [ ] global loading indicator => dev only component
- [ ] retry and retry delay
- [ ] paginated or lagged Queries
- [ ] fetch with an IntersectionObserver API
- [x] #2
- [x] #13
- [ ] tRPC integeration
